apiVersion: v1
kind: Pod
metadata:
  name: debug-tools
  namespace: avenger
  labels:
    app: debug-tools
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  containers:
  - name: debug-tools
    image: debug-tools:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
  restartPolicy: Never
