apiVersion: v1
kind: Pod
metadata:
  name: grpcurl-tester
  labels:
    app: grpcurl-tester
spec:
  containers:
  - name: grpcurl
    image: fullstorydev/grpcurl:latest
    # Use tail -f to keep the container running
    command: ["/bin/sh", "-c"]
    args: ["tail -f /dev/null"]
