apiVersion: v1
kind: Pod
metadata:
  name: grpcurl-tester
  labels:
    app: grpcurl-tester
spec:
  containers:
  - name: grpcurl
    # Use Alpine Linux with curl installed
    image: alpine:3.18
    # Install grpcurl in the container
    command: ["/bin/sh", "-c"]
    args:
      - |
        # Install required packages
        apk add --no-cache curl
        
        # Download and install grpcurl
        cd /tmp
        curl -L -o grpcurl.tar.gz https://github.com/fullstorydev/grpcurl/releases/download/v1.9.3/grpcurl_1.9.3_linux_x86_64.tar.gz
        tar -xzf grpcurl.tar.gz
        mv grpcurl /usr/local/bin/
        chmod +x /usr/local/bin/grpcurl
        
        # Verify installation
        grpcurl --version
        
        # Keep container running
        echo "grpcurl installed successfully. Container will remain running for testing."
        tail -f /dev/null
