# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"j\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x11\n\tserver_id\x18\x05 \x01(\t\"=\n\x13ListProductsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\"U\n\x14ListProductsResponse\x12*\n\x08products\x18\x01 \x03(\x0b\x32\x18.product.ProductResponse\x12\x11\n\tserver_id\x18\x02 \x01(\t2\xa2\x01\n\x0eProductService\x12\x41\n\nGetProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\"\x00\x12M\n\x0cListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTREQUEST']._serialized_start=26
  _globals['_PRODUCTREQUEST']._serialized_end=62
  _globals['_PRODUCTRESPONSE']._serialized_start=64
  _globals['_PRODUCTRESPONSE']._serialized_end=170
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=172
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=233
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=235
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=320
  _globals['_PRODUCTSERVICE']._serialized_start=323
  _globals['_PRODUCTSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
